version: 2

models:
  - name: stg_usaf_bases
    description: This model contains a list of USAF bases and their base codes. Each row represents a base. This model filters for only updated_records based on the most recent pull, also filters one base code out (buckey garrsion based on primary_key). 
    # columns:
    #   - name: base
    #     description: A four digit base code, representing each base.
    #     tests:
    #       - not_null
    #   - name: base_name
    #     description: The full name of the base.
    #     tests:
    #       - not_null
    #   - name: state
    #     description: The state name or equivalent location if outside the US.
    #     tests:
    #       - not_null
    #   - name: state_abv
    #     description: The abbreviation for the state or location for the base.
    #     tests:
    #       - not_null
    #   - name: phone_number
    #     description: A provided number, likely to the base operator. This column is not used.
    #   - name: primary_key
    #     description: A unique primary key representing this row. It is actually a surrogate key made up of an MD5 has of the base, and base_name columns.
    #     tests:
    #       - not_null
    #       - unique
    #   - name: updated_at
    #     description: The date time that the record was stored in the database.
    #     tests:
    #       - not_null

  - name: stg_usaf_cases_active
    description: This table contains basic info about the member who was charged in the case. Each row represents a member who has been charged. Renamed columns to standard. Filtered for active cases, and added the case_status and rank_type columns.
    # columns:
    #   - name: rank_abv
    #     description: The abbreviation for the members rank. Ex A1C
    #     tests:
    #       - not_null
    #       - unique
    #   - name: rank_full
    #     description: The full text rank of the member. Ex Airman First Class
    #     tests:
    #       - not_null
    #       - unique
    #   - name: rank_order
    #     description: I believe this is a number ordered by the individuals rank. I do not use this column.
    #     tests:
    #       - not_null
    #   - name: base_code
    #     desription: The base the member is associated with or has been charged at.
    #     tests:
    #       - not_null
    #   - name: first_name
    #     description: The first name of the member.
    #     tests:
    #       - not_null
    #   - name: last_name
    #     description:  The last name of the member.
    #     tests:
    #       - not_null
    #   - name: case_type
    #     description: The type of military judicial hearing the member is subject to.
    #     tests:
    #       - not_null
    #   - name: schd_trial_start_date
    #     description: The scheduled trial start date for the member, if it is still an active case.
    #     tests:
    #       - not_null
    #   - name: schd_trial_end_date
    #     description:  The scheduled trial end date for the member, if it is still an active case.
    #     tests:
    #       - not_null
    #   - name: estimated_trial_days
    #     description: The estimated number of days the trial is expected to last.
    #     tests:
    #       - not_null
    #   - name: foreign_key
    #     description: The provided foreign key, this maps to the unique case_id number for each case. Related to the usaf_cases_charges_raw dataset.
    #     tests:
    #       - not_null
    #   - name: primary_key
    #     description:  A unique primary key representing this row. It is actually a surrogate key made up of an MD5 has of the case_id, order, title, and name columns.
    #     tests:
    #       - not_null
    #       - unique
    #   - name: updated_at
    #     description: The date time that the record was stored in the database.
    #     tests:
    #       - not_null
    #   - name: case_status
    #     description: Describes the status of the case, either active or inactive.
    #     tests:
    #       - not_null
    #   - name: rank_type
    #     description: Wether the charged member is an officer or enlisted
    #     test:
    #       - not_null

  - name: stg_usaf_cases_charges
    description: This table contains a list of charges against members. Each row is a charge against a member, and there can be multiple rows per case id if a member in a case has multiple charges against them. Added data types.
    # columns:
    #   - name: case_id
    #     description:  A unique UUID representing each case. This is the core unique element to aggregate upon.
    #     tests:
    #       - not_null
    #   - name: code
    #     description: The UCMJ article code the member was charged with
    #     tests:
    #       - not_null
    #   - name: prefix
    #     description: Holds a prefix to the code column, for example  a prefix could be 'Attempted'. As in "attempted [Article 120]" 
    #   - name: primary_key
    #     description: A unique primary key representing this row. It is actually a surrogate key made up of an MD5 has of the case_id, and code columns.
    #     tests: 
    #       - not_null
    #       - unique
    #   - name: updated_at
    #     description: The date time that the record was stored in the database.
    #     tests:
    #       - not_null

  - name: stg_usaf_cases_inactive
    description: This table contains basic info about the member who was charged in the case. Each row represents a member who has been charged. Renamed columns to standard, filtered for inactive cases, casted data types, added rank type, added extrapolated sentences columns.
    # columns:
    #   - name: rank_abv
    #     description: The abbreviation for the members rank. Ex A1C
    #     tests:
    #       - not_null
    #       - unique
    #   - name: rank_full
    #     description: The full text rank of the member. Ex Airman First Class
    #     tests:
    #       - not_null
    #       - unique
    #   - name: rank_order
    #     description: I believe this is a number ordered by the individuals rank. I do not use this column.
    #     tests:
    #       - not_null
    #   - name: base_code
    #     desription: The base the member is associated with or has been charged at.
    #     tests:
    #       - not_null
    #   - name: first_name
    #     description: The first name of the member.
    #     tests:
    #       - not_null
    #   - name: last_name
    #     description:  The last name of the member.
    #     tests:
    #       - not_null
    #   - name: case_type
    #     description: The type of military judicial hearing the member is subject to.
    #     tests:
    #       - not_null
    #   - name: trial_url
    #     description: A URL link to the case information, if exists/provided.
    #   - name: trial_completion_date
    #     description: The completion date for the trial.
    #   - name: verdict
    #     description: The verdict rendered for the case.
    #     tests:
    #       - not_null
    #   - name: forum
    #     description: The forum the case was presided in.
    #     tests:
    #       - not_null
    #   - name: 
    #     description:
    #     tests:
    #   - name: 
    #     description:
    #     tests:
    #   - name: 
    #     description:
    #     tests:
    #   - name: 
    #     description:
    #     tests:
    #   - name: 
    #     description:
    #     tests:
    #   - name: 
    #     description:
    #     tests:
    #   - name: 
    #     description:
    #     tests:
    #   - name: 
    #     description:
    #     tests:
    #   - name: 
    #     description:
    #     tests:
    #   - name: foreign_key
    #     description: The provided foreign key, this maps to the unique case_id number for each case. Related to the usaf_cases_charges_raw dataset.
    #     tests:
    #       - not_null
    #   - name: primary_key
    #     description:  A unique primary key representing this row. It is actually a surrogate key made up of an MD5 has of the case_id, order, title, and name columns.
    #     tests:
    #       - not_null
    #       - unique
    #   - name: updated_at
    #     description: The date time that the record was stored in the database.
    #     tests:
    #       - not_null
    #   - name: case_status
    #     description: Describes the status of the case, either active or inactive.
    #     tests:
    #       - not_null
    #   - name: rank_type
    #     description: Wether the charged member is an officer or enlisted
    #     test:
    #       - not_null