version: 2

models:
  - name: stg_usaf_bases
    description: This model contains a list of USAF bases and their base codes. Each row represents a base. This model filters for only updated_records based on the most recent pull, also filters one base code out (buckey garrsion based on primary_key). 

  - name: stg_usaf_cases_active
    description: This table contains basic info about the member who was charged in the case. Each row represents a member who has been charged. Renamed columns to standard. Filtered for active cases, and added the case_status and rank_type columns.

  - name: stg_usaf_cases_charges
    description: This table contains a list of charges against members. Each row is a charge against a member, and there can be multiple rows per case id if a member in a case has multiple charges against them. Added data types.

  - name: stg_usaf_cases_inactive
    description: This table contains basic info about the member who was charged in the case. Each row represents a member who has been charged. Renamed columns to standard, filtered for inactive cases, casted data types, added rank type, added extrapolated sentences columns.
  
  - name: stg_usaf_cases_personnel

  - name: stg_usaf_charges
  
  - name: usaf_cases_active

  - name: usaf_cases_inactive

  - name: usaf_charges