version: 2

sources:
  - name: usaf_docket
    description: This data source represents the raw USAF docket data.
    loader: Python
    schema: dwh_bronze
    tables:

      - name: usaf_bases_raw
        description: This table contains a list of USAF bases and their base codes. Each row represents a base.

      - name: usaf_cases_info_raw
        description: This table contains basic info about the member who was charged in the case. Each row represents a member who has been charged.

      - name: usaf_cases_personnel_raw
        description: This table contains information about judicial members assigned to each case. Each row represents a list of judicial members for its respective case.

      - name: usaf_cases_charges_raw
        description: This table contains a list of charges against members. Each row is a charge against a member, and there can be multiple rows per case id if a member in a case has multiple charges against them.

      - name: usaf_charges_raw
        description: This table contains a list of UCMJ article codes. Each row represents a UCMJ article.
