version: 2

sources:
  - name: docket
    schema: dwh_bronze
    tables:
      - name: usaf_bases_raw
      - name: usaf_cases_info_raw
      - name: usaf_cases_personnel_raw
      - name: usaf_cases_charges_raw
      - name: usaf_charges_raw
