dbt_pipelines:
  outputs:

    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: postgres
      pass: postgres
      dbname: usaf_docket
      schema: dwh

    stage:
      type: postgres
      threads: 4
      host: "{{ env_var('DBT_ENV_SECRET_HOST') }}"
      port: 25060
      user: "{{ env_var('DBT_ENV_SECRET_USER') }}"
      pass: "{{ env_var('DBT_ENV_SECRET_PASS') }}"
      dbname: usaf_docket_stage
      schema: dwh

    prod:
      type: postgres
      threads: 4
      host: "{{ env_var('DBT_ENV_SECRET_HOST') }}"
      port: 25060
      user: "{{ env_var('DBT_ENV_SECRET_USER') }}"
      pass: "{{ env_var('DBT_ENV_SECRET_PASS') }}"
      dbname: usaf_docket_prod
      schema: dwh

  target: "{{ env_var('TARGET') }}"
