name: Continuous Integration Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  quality_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install CICD dependeies
        run: |
          python -m pip install --upgrade pip
          pip install pdm
          pdm install -d

      - name: Lint with ruff
        run: pdm run ruff ./data_pipelines

      - name: Test with Pytest
        run: pdm run pytest ./data_pipelines

      - name: SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
